# Generated by Django 5.1 on 2024-09-23 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order_table',
        ),
        migrations.AlterModelTable(
            name='orderproduct',
            table='orderproduct_table',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payment_table',
        ),
    ]
