# Generated by Django 5.1 on 2024-11-05 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_table_alter_orderproduct_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_created',
            new_name='is_ordered',
        ),
    ]
