# Generated by Django 5.1 on 2024-09-03 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_is_active'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='account_table',
        ),
    ]
