# Generated by Django 5.1 on 2024-11-02 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_cartitem_user_alter_cartitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
